apiVersion: v1 
kind: Service 
metadata:
  name: postgres-service
  labels: 
    app: postgres
spec: 
  #type: ClusterIP # If you don't provide a type, then it defaults to ClusterIP
  selector: 
    app: postgres
  ports: 
  - port: 5432
    targetPort: 5432 
