apiVersion: v1 
kind: Service
metadata:
  name: planet-service
  labels: 
    app: planet-service
spec: 
  type: LoadBalancer 
  selector: 
    app: planet-demo 
  ports: 
    - port: 7500
      targetPort: 7500
