apiVersion: v1
kind: Service 
metadata: 
  name: micro-service
  namespace: ben-space
  labels: 
    app: micro-service 
spec: 
  type: LoadBalancer #If you don't specify the type, it defaults to ClusterIP
  selector: 
    app: micro-demo
  ports: 
    - port: 7400
      targetPort: 7400 
