global:
  scrape_interval: 15s #Default scraping interval is 15 seconds if not specified.

scrape_configs:
  #Targetting itself, to make sure it's okay
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'micrometer-example'
    metrics_path: '/metrics' #Looks for this endpoint for all the metrics
    static_configs:
      - targets: ['app:7400'] #Referencing the name of the docker service in the compose file
        #Because docker compose creates a bridge network, they can reference each other!
